<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="UpdateTimeStamp" Id="{3ebf2d11-b075-4b1e-bfc5-6a6be67fc618}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION UpdateTimeStamp 
VAR_INPUT
	stUser : REFERENCE TO ST_USER;
END_VAR
VAR
	fbGETSYSTEMTIME : GETSYSTEMTIME;
	
	stFileTime : T_FILETIME;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[
fbGETSYSTEMTIME(timeLoDW =>stFileTime.dwLowDateTime ,
				timeHiDW =>stFileTime.dwHighDateTime );
				
stUser.dtTIME_STAMP:= FILETIME_TO_DT(fileTime := stFileTime); 

				

				
				
	]]></ST>
    </Implementation>
    <LineIds Name="UpdateTimeStamp">
      <LineId Id="3" Count="9" />
      <LineId Id="2" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>